name: Deploy Laravel App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Debugging - Test network connectivity to EC2 on port 22
      - name: Test connectivity to EC2
        run: |
          nc -zv 13.127.251.141 22 || echo "Cannot connect to EC2 on port 22"

      # Step 4: Add EC2 IP to known_hosts with retry on failure
      - name: Add EC2 IP to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.127.251.141 >> ~/.ssh/known_hosts || echo "ssh-keyscan failed, continuing without known_hosts update"

      # Step 5: Test SSH connection
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.127.251.141 'echo "SSH connection successful"' || echo "SSH connection failed"

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.127.251.141 << 'EOF'
            set -e
            cd /var/www/laravel-aws
            git pull https://github.com/Mayank0851/laravel-aws.git | tee git_pull.log
            composer install --no-interaction --prefer-dist --optimize-autoloader | tee composer_install.log
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            npm install | tee npm_install.log
            npm run build | tee npm_build.log
            php artisan migrate --force | tee migrate.log
            php artisan optimize | tee optimize.log
            sudo systemctl daemon-reload
            sudo service nginx restart
            echo "Deployment complete!"
            curl -f http://localhost || echo "Application is not responding"
          EOF



        
