name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Specify your PHP version
          extensions: mbstring, xml, dom, curl, zip  # Add any required extensions

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Copy files to EC2
        uses: scp-action/scp-action@v2
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance's public IP
          username: ${{ secrets.EC2_USER }}  # Your SSH username
          key: ${{ secrets.EC2_SSH_KEY }}  # Your SSH private key (base64 encoded)
          source: "."
          target: "/var/www/laravel-aws"  # Your application path on the server

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/laravel-aws
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
