name: Deploy Laravel App

on:
    push:
        branches:
            - main # Adjust this if you're using a different branch for deployment

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ubuntu@13.202.92.159 << 'EOF'
                    cd /var/www/laravel-app  # This is now the correct path
                    git pull git@github.com:imYashGupta/Rentique.git  # Use SSH instead of HTTPS
                    composer install --no-interaction --prefer-dist --optimize-autoloader  # Install/update PHP dependencies
                    npm install
                    npm run build
                    php artisan migrate --force  # Apply database migrations
                    php artisan optimize  # Optimize config
                    sudo systemctl daemon-reload  # Reload systemd (to apply any changes to Nginx)
                    sudo service nginx restart  # Restart Nginx to apply new changes
                  EOF
