name: Laravel CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, xml, bcmath, zip  # Add any required PHP extensions

      # Step 3: Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Step 4: Install dependencies using Composer
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

      # Step 5: Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 6: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 7: Install Node.js packages
      - name: Install Node.js packages
        run: npm install

      # Step 8: Build assets using Vite
      - name: Build assets
        run: npm run build

      # Step 9: Test SSH Connection to EC2
      - name: Test SSH Connection to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -v -o StrictHostKeyChecking=no "$USER@$HOST" echo "Connection successful"

      # Step 10: SSH into the server and run post-deployment commands
      - name: Run post-deployment commands
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Start the SSH agent
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          
          # SSH command
          ssh -v -o StrictHostKeyChecking=no "$USER@$HOST" << 'EOF'
            cd /var/www/laravel
            
            # Pull the latest changes from the repository using the GITHUB_TOKEN
            git pull https://${{ secrets.GIT_TOKEN }}@github.com/Mayank0851/laravel-aws.git
            
            # Run Laravel commands
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart nginx
          EOF
